version: '3.8'

services:
  frontend:
    build:
      context: .  # Используем корневую директорию для сборки фронтенда
      dockerfile: Dockerfile  # Dockerfile для фронтенда находится в корне проекта
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./psyho_bot  # Путь к директории бэкенда
      dockerfile: Dockerfile  # Dockerfile для бэкенда находится в папке psyho_bot
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
